Add Meltano support
dbt-labs/jaffle-shop-template pull request #9
Opened 2023-03-13 20:24 UTC by aaronsteers

This PR echoes the changes on the `MeltanoLabs` fork:

- https://github.com/MeltanoLabs/jaffle-shop-template/pull/1/files

Most notably:

The source data can now be ingested via `tap-jaffle-shop`, which is built upon `jafgen`.

All dbt commands can still be called directly, but when wrapped with Meltano they include automatic environment isolation across all tools in the data stack.

Meltano also provides streamlined manner of working with Evidence.

The readme has been expanded with Meltano-specific instructions, and additional sample invocation info can be found in the GitHub CI workflow.

Sample commands:

```
# Do all the things:
meltano run elt
meltano invoke dbt:build
meltano invoke evidence:build-strict
```

And BI dev can happen with:

```
meltano invoke evidence:dev
```

This PR builds on changes in:

- https://github.com/dbt-labs/jaffle-shop-template/pull/8
- https://github.com/dbt-labs/jaffle-shop-template/pull/87

and should be merged/reviewed after those ones in order to have a smaller PR.

2023-03-29 22:58 UTC, aaronsteers commented on reports/pages/index.md
> +
```suggestion
```

2023-03-29 23:26 UTC, aaronsteers commented
@gwenwindflower - I've scaled this way back so the PR now just focuses on EL.

I still have some work to do to make sure env vars and database paths are all aligned. Once CI passes, this should be ready for review though.

2023-03-29 23:28 UTC, aaronsteers commented on .github/workflows/ci.yml
> +        run: dbt build
These are still identical as before, except I added step names for improved readability in CI history.

2023-03-29 23:46 UTC, aaronsteers commented
CI Pipelines are now succeeding. 

@gwenwindflower - Do you squash PRs as a rule? We definitely would not want to merge commit this PR, since it has so many commits. Happy to squash on my side if helpful.

Also, my latest commit here https://github.com/dbt-labs/jaffle-shop-template/pull/9/commits/90de06597aea6a2b97723bec230f547ebf1f6494 removes the raw data files and the dynamic behavior toggle for external tables, instead assuming the raw data has already landed. Once I removed external table support, I was able to change the default raw schema for the tap to the same as you had as the default elsewhere (`'jaffle_raw'` instead of `'tap_jaffle_shop'` I had previously.

I'm happy to revert and bring those back, but I thought I'd just include those deletions here so it is certain that the pipeline data is coming from the EL process and not the seed CSV files.

2023-03-29 23:57 UTC, aaronsteers commented on .github/workflows/ci.yml
> +          cache: 'pip'
Not necessary for this PR, but this gives a nice little speed boost if dependencies haven't changed since last run.

2023-03-30 00:02 UTC, aaronsteers commented
Pipeline is green again, ready for review. Note that 1 year of data takes approximately 3 minutes and total CI duration is still <5 minutes in total:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/18150651/228694542-b2d91a70-739b-4f62-b4c9-838b8fade72a.png">

2023-03-31 13:45 UTC, gwenwindflower requested changes
looking wonderful, only one quick thing and one nebulous thing:

1. can we add `&& meltano run el` to the `postCreateCommand` so the raw data is ready when they drop in and they can `dbt build`?
2. running the EL job felt oddly slow to me? it took longer to build the tables than to run the simulation? curious what's taking the most time in that process and if there's anything we can do to speed it up?

2023-04-01 02:51 UTC, aaronsteers commented
@gwenwindflower - I found a small performance optimization that will significantly boost tap performance.

I'll bump the tap version once that update is available and I will update the postCreateScript as you proposed.

Will post back here with updated perf numbers when that's done. 👍

2023-04-07 01:19 UTC, gwenwindflower approved these changes

2023-04-07 01:19 UTC, merged